import {ProjectClassName} from "../../common/className/ClassName";
import {ABBProject} from "./specific/ABBProject";
import {ASProject} from "./specific/ASProject";
import {CARTProject} from "./specific/CARTProject";
import {CONSTRProject} from "./specific/CONSTRProject";
import {CRPProject} from "./specific/CRPProject";
import {CTProject} from "./specific/CTProject";
import {DISUPProject} from "./specific/DISUPProject";
import {DPDProject} from "./specific/DPDProject";
import {DSDProject} from "./specific/DSDProject";
import {ESProject} from "./specific/ESProject";
import {EVENTProject} from "./specific/EVENTProject";
import {FINProject} from "./specific/FINProject";
import {GRProject} from "./specific/GRProject";
import {HRProject} from "./specific/HRProject";
import {ITFProject} from "./specific/ITFProject";
import {ITSProject} from "./specific/ITSProject";
import {LAUNCHProject} from "./specific/LAUNCHProject";
import {MABProject} from "./specific/MABProject";
import {MOLProject} from "./specific/MOLProject";
import {NBUProject} from "./specific/NBUProject";
import {NCSProject} from "./specific/NCSProject";
import {OPTIMProject} from "./specific/OPTIMProject";
import {PRODProject} from "./specific/PRODProject";
import {PROTProject} from "./specific/PROTProject";
import {RDProject} from "./specific/RDProject";
import {REGProject} from "./specific/REGProject";
import {RNAProject} from "./specific/RNAProject";
import {SMProject} from "./specific/SMProject";
import {TRANSProject} from "./specific/TRANSProject";
import {TRFProject} from "./specific/TRFProject";
import {TSDProject} from "./specific/TSDProject";

export interface ProjectClassNameMap {
    [ProjectClassName.SM]: SMProject;
    [ProjectClassName.REG]: REGProject;
    [ProjectClassName.PROD]: PRODProject;
    [ProjectClassName.NCS]: NCSProject;
    [ProjectClassName.NBU]: NBUProject;
    [ProjectClassName.LAUNCH]: LAUNCHProject;
    [ProjectClassName.ITS]: ITSProject;
    [ProjectClassName.ITF]: ITFProject;
    [ProjectClassName.HR]: HRProject;
    [ProjectClassName.GR]: GRProject;
    [ProjectClassName.FIN]: FINProject;
    [ProjectClassName.EVENT]: EVENTProject;
    [ProjectClassName.ES]: ESProject;
    [ProjectClassName.CT]: CTProject;
    [ProjectClassName.CONSTR]: CONSTRProject;
    [ProjectClassName.TRF]: TRFProject;
    [ProjectClassName.DPD]: DPDProject;
    [ProjectClassName.DSD]: DSDProject;
    [ProjectClassName.ABB]: ABBProject;
    [ProjectClassName.MAB]: MABProject;
    [ProjectClassName.MOL]: MOLProject;
    [ProjectClassName.PROT]: PROTProject;
    [ProjectClassName.CART]: CARTProject;
    [ProjectClassName.RNA]: RNAProject;
    [ProjectClassName.TRANS]: TRANSProject;
    [ProjectClassName.DISUP]: DISUPProject;
    [ProjectClassName.OPTIM]: OPTIMProject;
    [ProjectClassName.TSD]: TSDProject;
    [ProjectClassName.RD]: RDProject;
    [ProjectClassName.AS]: ASProject;
    [ProjectClassName.CRP]: CRPProject;
}
